feat: replace hardcoded server config with TOML configuration
garyo/lsp-multiplexer pull request #5
Opened 2024-11-30 15:59 UTC by imprvhub

- Remove hardcoded server configuration from main code
- Add server configuration via TOML files
- Add config file loading with fallback paths
- Create ServerConfig.from_config method for parsing
- Update project dependencies to include tomli

Closes #4

2024-12-02 15:36 UTC, garyo requested changes
Looks great to me. One minor change, otherwise ready to merge.

2024-12-02 15:36 UTC, garyo commented on lsp-multiplexer.py
> +    multiplexer = LSPMultiplexer(server_configs)
The only change I see is now you're initializing LSPMultiplexer with a list of ServerConfigs, so you should adjust the type signature of LSPMultiplexer.__init__ to reflect that. For instance:
```python
    def __init__(self, server_configs: List[ServerConfig]) -> None:
```
With that, `pyright` should pass again. (Hmm, I should set up a quick pyright test CI action.)

2024-12-02 16:45 UTC, imprvhub commented on lsp-multiplexer.py
> +    multiplexer = LSPMultiplexer(server_configs)
Done! [7520b78](https://github.com/garyo/lsp-multiplexer/pull/5/commits/7520b7882ded0445d5b84a3cb2db2d932c69d74f)

2024-12-03 14:04 UTC, garyo approved these changes
Thanks!

2024-12-03 14:04 UTC, merged